development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: garage
  pool: 5
  username: leoo
  password: leoomysql
  host: localhost

#development:
#  adapter: postgresql
#  encoding: unicode
#  database: garage
#  pool: 5
#  username: leoo
#  password: leoo

test:
  adapter: postgresql
  encoding: unicode
  database: test-todo-on-rails
  pool: 5
  username: leoo
  password: leoo

production:
  adapter: postgresql
  encoding: unicode
  database: todo-on-rails
  pool: 5
  username: leoo
  password: leoo
