development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: garage
  pool: 5
  username: leoo
  password: leoomysql
  host: localhost

#development:
#  adapter: postgresql
#  encoding: unicode
#  database: garage
#  pool: 5
#  username: leoo
#  password: leoo

#test:
#  adapter: sqlite3
#  database: db/test.sqlite3
#  pool: 5
#  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: garage-test
  pool: 5
  username: leoo
  password: leoomysql
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: todo-on-rails
  pool: 5
  username: leoo
  password: leoo
